### ISSUE TITLE
Rendering of "f" in heavy weights

### ISSUE THREAD

**Issue by m4rc1e** [TypeNetwork/Raleway#12]
![Desktop_Windows_10_chrome_69 0_](https://user-images.githubusercontent.com/7525512/72255270-34adeb80-35fe-11ea-951e-bea7980f5f0b.gif)

![raleway_f](https://user-images.githubusercontent.com/7525512/72255405-8b1b2a00-35fe-11ea-88f2-eefb79109b18.gif)

Previous "f" has a lower crossbar. New "f" has correct crossbar placement but ascender feels too short.

**Comment by pichotta** [comment]
solve using VTT hinting and compile using VTT Lib
