### ISSUE TITLE
Components: Rotated or Scaled

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Raleway#13]
@mikedug  @m4rc1e
These glyphs in Raleway have components which have been rotated or scaled. Confirming they can be decomposed.

 'Raleway Thin' 
	 m in sha-cy.loclBGR
	 Che-cy in Shha-cy
	 v in el-cy.loclBGR
	 quoteleft in quotedblright
	 quoteleft in quotedblright
	 question in questiondown
	 quoteleft in quoteright

 'Raleway Black Italic'
	 m in sha-cy
	 two.numr in twothirds
	 two.dnom in onehalf
	 question in questiondown
	 circumflexcomb in hcircumflex
	 acutecomb in Aringacute
	 quoteleft in quoteright

 'Raleway Black' 
	 m in sha-cy.loclBGR
	 Che-cy in Shha-cy
	 v in el-cy.loclBGR
	 quoteleft in quotedblright
	 quoteleft in quotedblright
	 question in questiondown
	 acutecomb in Aringacute
	 quoteleft in quoteright

'Raleway Medium' 
	 m in sha-cy.loclBGR
	 Che-cy in Shha-cy
	 v in el-cy.loclBGR
	 two.numr in twothirds
	 two.dnom in onehalf
	 quoteleft in quotedblright
	 quoteleft in quotedblright
	 question in questiondown
	 acutecomb in Aringacute
	 quoteleft in quoteright

Raleway Medium Italic
	 m in sha-cy
	 two.numr in twothirds
	 two.dnom in onehalf
	 question in questiondown
	 circumflexcomb in hcircumflex
	 acutecomb in Aringacute
	 quoteleft in quoteright

Raleway Thin Italic
	 m in sha-cy
	 question in questiondown
	 quoteleft in quoteright

**Comment by mikedug** [comment]
this is fine by me, and I can hint these glyphs as uniques.

**Comment by pichotta** [comment]
complex transformations resolved and made compatible
