### ISSUE TITLE
Prepare Variable Font Outlines for Hinting

### ISSUE THREAD

**Issue by mikedug** [TypeNetwork/Raleway#16]
Please review Variable Font, Raleway[wght].ttf for outline consistency. 
All glyph outlines for all variations need to be reviewed for issues of consistency, to ensure good hinting 
Example 1 : Cap H Variation in Bold. Vertical and horizontals are incorrect. See right hand side of left stem, 4 points should be at same x coordinates, but are not. This is an issue for many many outlines in the font

Example 2 : Unicode 0308 (dieresis accent) Bold variation outlines are badly off for vertical and horizontal alignments, resulting in non square or rectangle dots. 

One composite issue , Uni 04AB, GID 763, is incorrectly made, importing two separate base glyphs resulting in a double outline

**Comment by pichotta** [comment]
Hi @mikedug 

Could you clarify about Example 1.  Is it in the Bold? or master Black?   
Which point indexes, or values?

<img width="943" alt="H in Raleway Bold" src="https://user-images.githubusercontent.com/6576107/78586754-e594e280-7809-11ea-9445-9b5d96fca374.png">

**Comment by mikedug** [comment]
I am seeing the issue when I view the Bold Variation in VTT. The points , 5 4 9 8 are not aligned. Also see horizontal 
![7F800CD1-9BDD-4304-94F9-25DE04CE8173](https://user-images.githubusercontent.com/55890745/78587735-4ab1fd80-7835-11ea-8930-a6c89b30da60.jpeg)

**Comment by pichotta** [comment]
I certainly see the mis-alignment in the VTT example Bold /H posted.  I do not see it in the source data where the measurements and appearance is aligned. We will have to investigate.

**Comment by mikedug** [comment]
Thank you. It is very obvious in the dieresis example, so that might also give you some clues. In the meantime I will continue to complete the hinting which is due per schedule for the the end of this week.

**Comment by pichotta** [comment]
@moyogo 
See above for differences in display between the UFO and VTT.  The /dieresiscomb point indexes; alignment measurements; component order looks okay in the masters.   

![Bold dieresiscomb 2020-04-06 at 5 02 47 PM](https://user-images.githubusercontent.com/6576107/78605217-22240680-7829-11ea-8af3-437faabbd102.png)

**Comment by pichotta** [comment]
Hi @mikedug 

I have not been able to replicate this Issue in the .ufo, .ttf, or VF.ttf.  See this snapshot in https://www.axis-praxis.org/samsa/  looking at the Bold /H and /uni0308
Is there something happening in VTT?

cc: @m4rc1e, @moyogo, @djrrb 

![Raleway Bold 2020-04-08 at 9 05 15 AM](https://user-images.githubusercontent.com/6576107/78788105-51e22400-7979-11ea-9fcb-4e98bcc6a313.png)

![Raleway Bold 2020-04-08 at 9 06 52 AM](https://user-images.githubusercontent.com/6576107/78788115-56a6d800-7979-11ea-954e-1d069e90385e.png)

**Comment by mikedug** [comment]
Thanks for testing. I did some testing on axis praxis, and am not seeing the outline errors. I will keep testing, and in the meantime will continue to Hint in VTT as this does not appear to be causing issues in the hinted output. 

Could you test the composite issue , Uni 04AB, GID 763, is incorrectly made, importing two separate base glyphs resulting in a double outline, at least that is what I see in VTT

![6AD96744-EA4F-4709-B5E1-66CC555B2EB0](https://user-images.githubusercontent.com/55890745/78796698-963be700-79ae-11ea-9a7f-1909f3a7f73c.jpeg)

**Comment by pichotta** [comment]
Hi @mikedug 

An adjustment was made to the outline of the /uni04AB in the roman and italic. A new build was committed. Does this fix the double outline issue in VTT?

**Comment by mikedug** [comment]
Am still seeing the same double outline issue. Perhaps if this glyph could be decomposed and built as a unique glyph, I can rehint?

**Comment by pichotta** [comment]
The glyph was decomposed.  I can look again and make a different outline adjustment.

**Comment by mikedug** [comment]
VTT is still reading uni 04AB (gid 763) as a composite glyph, referencing 2 glyphs, gid 653 and gid 695 to make the composite.

**Comment by pichotta** [comment]
Perhaps it is also reading this other variant? /esdescender-cy.loclBSH   I will decompose that one as well.

**Comment by pichotta** [comment]
@mikedug  
Fix to localized variant form for Bashkir support /esdescender-cy.loclBSH to accompany /esdescender-cy (uni04AB). Change made for both cases in roman and italic. There was a duplicate component on top of each other which probably accounts for the display in VTT.  
Made new build using build.sh.

![double component 2020-04-09 at 8 47 47 PM](https://user-images.githubusercontent.com/6576107/78954090-00d14d80-7aa9-11ea-9bb9-c610f24bb0b1.png)

**Comment by mikedug** [comment]
Thank you for doing the investigation and for making the fix. I can confirm that the outlines are now ok, and I can take the Hinting forward from here with the new font builds. Thanks Mike
