### ISSUE TITLE
fix-non-marks sources do not match what Mike hinted

### ISSUE THREAD

**Issue by m4rc1e** [TypeNetwork/Raleway#19]
This is the exact reason why I **hate** manual hinting solutions. The branch fix-non-marks which has @moyogo's fix for the GDEF marks doesn't match the hinting Mike provided in #17.

**Comment by moyogo** [comment]
This was fixed by b3dce4a965aefd37eac984a319dd8852a4551fcd in m4rc1e/hinted.
