### ISSUE TITLE
Glyph issues

### ISSUE THREAD

**Issue by m4rc1e** [TypeNetwork/Raleway#5]
Glyphs with carons are mispositioned in darker weights in both the romans and italics.

![caron_shift_italic](https://user-images.githubusercontent.com/7525512/68385846-952e3180-0152-11ea-8adc-b18bd106055c.gif)

![caron_shift](https://user-images.githubusercontent.com/7525512/68385847-952e3180-0152-11ea-937d-3a35f67f3a0c.gif)

Some marks in the italic are mispositioned

![marks](https://user-images.githubusercontent.com/7525512/68386071-2f8e7500-0153-11ea-860e-e13b08235cce.gif)

Are you folks running QAs or are you solely relying on myself to check your work?

**Comment by m4rc1e** [comment]
Acutes still look off to me.

![acute](https://user-images.githubusercontent.com/7525512/69141109-ec6dc380-0abb-11ea-94df-562dbaed2dce.gif)

@pichotta it may be best for both of us to sign off pull requests before they get merged.

**Comment by cjdunn** [comment]
@m4rc1e see latest reports here:
https://github.com/TypeNetwork/Raleway/pull/7#issuecomment-556230678

I think the accents are more consistent now and any remaining shifts look like improvements, rather than regressions. Please let us know if these work for you.

**Comment by m4rc1e** [comment]
Can you check MM compat of all 4s in the fractions?

<img width="138" alt="Screenshot 2019-11-25 at 11 59 22" src="https://user-images.githubusercontent.com/7525512/69538837-196a1c80-0f7b-11ea-9e55-2a1ee19e3230.png">

It may just be a FreeType issue.

**Comment by cjdunn** [comment]
@m4rc1e good catch. This if fixed via my PR here:
https://github.com/TypeNetwork/Raleway/pull/9
